name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'
  release:
    types: [created]

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Get Version
        id: get_version
        run: |
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Install, Test, and Build
        run: |
          npm install
          npm test
          npm run build
          zip -r ./dist/rustore-${{ env.VERSION }}.zip ./dist

      - name: Upload Assets to Release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_PR }} # add write permission https://github.com/romankurnovskii/REPOSITORY/settings/actions
        with:
          files: |
            ./dist/rustore-${{ env.VERSION }}.zip
          draft: false
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true
